import "./globals.css"
import Navbar from "./_components/Navbar"

import { Poppins } from "next/font/google"
import Footer from "./_components/Footer"

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  fallback: ["system-ui", "Helvetica Neue", "Helvetica", "Arial"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <Navbar />
        <section>{children}</section>
        <Footer />
      </body>
    </html>
  )
}
