import "./globals.css"
import Navbar from "./_components/Navbar"

import { Italiana, Karla, Old_Standard_TT } from "next/font/google"

import Footer from "./_components/Footer"
import Hero from "./_components/Hero"

const old_standard_tt = Old_Standard_TT({
  subsets: ["latin"],
  variable: "--font-old-standard-tt",
  fallback: ["system-ui", "Helvetica Neue", "Helvetica", "Arial"],
  weight: ["400"],
  display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className={`${old_standard_tt.variable} font-oldStandard`}>
        <div className="relative">
          {/* <div className="z-10 fixed w-full">
            <Navbar />
          </div> */}
          <div className="bg-img z-0 sm:h-screen" />

          <div className="z-0 transform -translate-y-[0px]">
            <section>{children}</section>
          </div>

          <div className="z-0 transform -translate-y-[0px] bg-white">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
